### ISSUE TITLE
Comment box action items

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Talk-Frontend#5]
Action items for the comment box:

- [x] Fix bug with highlight-capability for bold/italics when highlighting entire box
- [x] Change over to Github-flavored markdown to support tables
- [x] Change insert image/link buttons to add markdown (instead of opening option below menu) and highlight the URL portion of the text
- [x] Add additional markdown-assist buttons to mostly match current Talk's functionality
- [x] Remove "clear image" button and incorporate as part of "featured image" dropdown
- [x] Universalize "focus image" as "featured image" (for now)
- [x] Change "select an image" to "featured image"
- [x] Rename "insert image link" as "insert image"
- [x] For clarity, move "preview" and "help" below the text box if possible
- [x] Investigate degree to which markdown supports image resizing

**Comment by aweiksnar** [comment]
@DarrenMcRoy these should be all set now

**Comment by DarrenMcRoy** [comment]
After testing it for a little bit, here are some more things to fix:

- [] After highlighting text and clicking "insert link," the formerly highlighted text should populate the title field, not the URL field, and the newly highlighted part should be where the URL goes
- [] Replace "Example Title" with "Example Text"
- [] Replace "Example Image" with "Example Alt Text"
- [] The "bold," "italics," "strikethrough" and "heading" buttons all introduce extra spaces around the text when they are clicked; they should not do this.
- [] Highlighting text and clicking "italics" should not replace all the text with the words "Italic Text;" it should work like the Bold button.
- [] Replace "Horizontal Rule" with "Insert Line"
- [] Selecting "clear image" after selecting an image should clear the image, not replace it with a broken one
- [] Add button for creating tables? (Perhaps for now this just creates a 2x2 table?)
- [] Add more information to "help;" i.e., how to add image resizing
- [] Fix problem: adding a single line break between paragraphs does not add that line break in the Preview. It takes hitting "return" twice (adding two line breaks) in the text field to create the (double-spaced) line break in Preview.
- [] No matter how many line breaks are added before a quote, the Preview will only display two line breaks.

Going to stop here for now. Will do further testing after these are fixed; it would definitely help if you do, too! :-)

**Comment by DarrenMcRoy** [comment]
Closing; completed.
