### ISSUE TITLE
Talk and Talk-Frontend status

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Talk-Frontend#7]
Looking forward to the new Talk. What's the projected timeline look like for implementation? Will it be ready for primetime by March?

**Comment by aweiksnar** [comment]
Things should be ready for users by March. The timeline should be fairly consistent with that of panoptes. 

The frontend of talk will live inside of the panoptes frontend, so everything will be integrated. After the api layer is ready I'll start adding in the talk parts of the site.

**Comment by mkosmala** [comment]
Sounds good!
